apiVersion: v2
name: sentry
description: A Helm chart for Kubernetes
type: application
version: 19.1.0
appVersion: 23.5.0
dependencies:
  - name: memcached
    repository: https://charts.bitnami.com/bitnami
    version: 6.1.5
    condition: sourcemaps.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 16.12.1
    condition: redis.enabled
  - name: kafka
    repository: https://charts.bitnami.com/bitnami
    version: 22.1.3
    condition: kafka.enabled
  - name: clickhouse
    repository: https://charts.bitnami.com/bitnami
    version: 3.4.1
    condition: clickhouse.enabled
  - name: zookeeper
    repository: https://charts.bitnami.com/bitnami
    version: 11.4.2
    condition: zookeeper.enabled
  - name: rabbitmq
    repository: https://charts.bitnami.com/bitnami
    version: 11.15.3
    alias: rabbitmq
    condition: rabbitmq.enabled
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 12.5.1
    condition: postgresql.enabled
  - name: nginx
    repository: https://charts.bitnami.com/bitnami
    version: 12.0.4
    condition: nginx.enabled
maintainers:
  - name: sentry-kubernetes
