apiVersion: v2
appVersion: 7.3.0
description: A Helm chart for Confluent Zookeeper on Kubernetes
home: https://github.com/ricardo-aires/helm-charts/tree/main/charts/zookeeper
icon: https://svn.apache.org/repos/asf/comdev/project-logos/originals/zookeeper.svg
keywords:
- zookeeper
- confluent
maintainers:
- email: ricardoaireshenriques@gmail.com
  name: Ricardo Henriques
  url: https://github.com/ricardo-aires
name: zookeeper
sources:
- https://github.com/ricardo-aires/helm-charts
- https://docs.confluent.io/platform/current/zookeeper/deployment.html
- https://zookeeper.apache.org/doc/current/index.html
- https://hub.docker.com/r/confluentinc/cp-zookeeper
type: application
version: 0.2.0
